/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.categoria;

import model.Categoria;

/**
 *
 * @author bruno_azzi
 */
public class ItemMenuCategoria extends javax.swing.JPanel {
    Categoria categoria = new Categoria();
    /**
     * Creates new form ItemMenuCategoria
     */
    public ItemMenuCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setMaximumSize(new java.awt.Dimension(150, 150));
        setMinimumSize(new java.awt.Dimension(150, 150));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel1.setText("<Description>");

        jLabelFoto.setEnabled(false);
        jLabelFoto.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelFoto.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabelFoto.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFoto;
    // End of variables declaration//GEN-END:variables

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
        jLabelFoto.setIcon(categoria.getFotoCategoria().getFoto().getIcon());
        jLabel1.setText(categoria.getNome());
    }
}
