/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.buychart;

import control.FormaDePagamentoControl;
import control.ProdutoControl;
import control.VendaControl;
import control.VendaEfetuadaControl;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import messages.ConfirmMessages;
import messages.Titles;
import messages.Warnings;
import model.Formadepagamento;
import model.Produto;
import model.Venda;
import model.Vendaefetuada;
import utilidades.Mensagens;
import utilidades.Tela;

/**
 *
 * @author brunoazzi
 */
public class TelaCarrinhoDeCompras extends javax.swing.JFrame {

    int x = 10;
    int y = 10;
    public ArrayList<Produto> produtosNoCarrinhoDeCompras = CarrinhoDeCompras.getProdutos();

    /**
     * Creates new form TelaCarrinhoDeCompras
     */
    public TelaCarrinhoDeCompras() {
        initComponents();
        initItensDoCarrinhoDeCompras();
        jComboBoxQuantidadeDeParcelas.setVisible(false);
        jLabelQuantidadeDeParcelas.setVisible(false);
        CarrinhoDeCompras.setTela(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelCarrinho = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioMasterCard = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonVisa = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonDinheiro = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonPayPal = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTotalDaCompra = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelQuantidadeDeParcelas = new javax.swing.JLabel();
        jComboBoxQuantidadeDeParcelas = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrinho de Compras");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                atualizaTotalDaCompra(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setMaximumSize(Tela.screenSizeTratado());
        jPanel2.setMinimumSize(Tela.screenSizeTratado());
        jPanel2.setPreferredSize(Tela.screenSizeTratado());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelCarrinho.setBackground(new java.awt.Color(51, 102, 255));
        jPanelCarrinho.setPreferredSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanelCarrinhoLayout = new javax.swing.GroupLayout(jPanelCarrinho);
        jPanelCarrinho.setLayout(jPanelCarrinhoLayout);
        jPanelCarrinhoLayout.setHorizontalGroup(
            jPanelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, Short.MAX_VALUE, Short.MAX_VALUE)
        );
        jPanelCarrinhoLayout.setVerticalGroup(
            jPanelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, Short.MAX_VALUE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelCarrinho);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Master-Card-Black.png"))); // NOI18N

        buttonGroup1.add(jRadioMasterCard);
        jRadioMasterCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMasterCardActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visa-Balck.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonVisa);
        jRadioButtonVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVisaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Money-Black.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonDinheiro);
        jRadioButtonDinheiro.setSelected(true);
        jRadioButtonDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDinheiroActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Paypal-Black.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonPayPal);
        jRadioButtonPayPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPayPalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Formas de Pagamento:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Fechar Compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelTotalDaCompra.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelTotalDaCompra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalDaCompra.setText("<total>");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total:");

        jLabelQuantidadeDeParcelas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantidadeDeParcelas.setText("Quantidade de Parcelas:");

        jComboBoxQuantidadeDeParcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A vista" }));

        jButton2.setText("Desistir da Compra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonPayPal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonVisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioMasterCard)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelQuantidadeDeParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxQuantidadeDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTotalDaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButtonDinheiro, jRadioButtonPayPal, jRadioButtonVisa, jRadioMasterCard});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioMasterCard, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelQuantidadeDeParcelas)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxQuantidadeDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalDaCompra)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, jLabelTotalDaCompra});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jRadioButtonDinheiro, jRadioButtonPayPal, jRadioButtonVisa, jRadioMasterCard});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(CarrinhoDeCompras.getProdutos().size() <= 0){
            JOptionPane.showMessageDialog(this, 
                    Warnings.CARRINHO_VAZIO.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            if (areUSure()) {
                Venda venda = new Venda();
                venda.setData(new Date());
                venda.setFormaDePagamento(getFormaDePagamento());
                venda.setQuantidadeDeParcelas(1);
                venda.setTotal(CarrinhoDeCompras.getValorTotalDaCompra());
                VendaControl.add(venda);

                ArrayList<Produto> produtos = CarrinhoDeCompras.getProdutos();
                for (Produto produto : produtos) {
                    Vendaefetuada vendaefetuada = new Vendaefetuada();
                    vendaefetuada.setProduto(produto);
                    vendaefetuada.setQuantidadeVendida(CarrinhoDeCompras.getQuantidadeDoProduto(produto));
                    vendaefetuada.setVenda(venda);
                    VendaEfetuadaControl.add(vendaefetuada);

                    produto.setQuantidade(produto.getQuantidade() - CarrinhoDeCompras.getQuantidadeDoProduto(produto));
                    ProdutoControl.add(produto);
                }

                JOptionPane.showMessageDialog(this,
                        Mensagens.COMPRA_SUCESSO.getDescricao(),
                        Titles.SUCESSO.getDescricao(),
                        JOptionPane.INFORMATION_MESSAGE);

                CarrinhoDeCompras.removeAllProdutosFromCarrinho();
                CarrinhoDeCompras.updateTelaDeCarrinhos();
                this.dispose();
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this,
                    Warnings.COMPRA_INSUCESSO.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPayPalActionPerformed
        jComboBoxQuantidadeDeParcelas.setVisible(false);
        jLabelQuantidadeDeParcelas.setVisible(false);
    }//GEN-LAST:event_jRadioButtonPayPalActionPerformed

    private void jRadioButtonDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDinheiroActionPerformed
        jComboBoxQuantidadeDeParcelas.setVisible(false);
        jLabelQuantidadeDeParcelas.setVisible(false);
    }//GEN-LAST:event_jRadioButtonDinheiroActionPerformed

    private void jRadioButtonVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVisaActionPerformed
        jComboBoxQuantidadeDeParcelas.setVisible(true);
        jLabelQuantidadeDeParcelas.setVisible(true);
    }//GEN-LAST:event_jRadioButtonVisaActionPerformed

    private void jRadioMasterCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMasterCardActionPerformed
        jComboBoxQuantidadeDeParcelas.setVisible(true);
        jLabelQuantidadeDeParcelas.setVisible(true);
    }//GEN-LAST:event_jRadioMasterCardActionPerformed

    private void atualizaTotalDaCompra(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_atualizaTotalDaCompra
        jLabelTotalDaCompra.setText(CarrinhoDeCompras.getValorTotalDaCompra().toString());
    }//GEN-LAST:event_atualizaTotalDaCompra

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CarrinhoDeCompras.removeAllProdutosFromCarrinho();
        CarrinhoDeCompras.updateTelaDeCarrinhos();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarrinhoDeCompras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxQuantidadeDeParcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelQuantidadeDeParcelas;
    private javax.swing.JLabel jLabelTotalDaCompra;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCarrinho;
    private javax.swing.JRadioButton jRadioButtonDinheiro;
    private javax.swing.JRadioButton jRadioButtonPayPal;
    private javax.swing.JRadioButton jRadioButtonVisa;
    private javax.swing.JRadioButton jRadioMasterCard;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initItensDoCarrinhoDeCompras() {
        x = 10;
        y = 10;

        jPanelCarrinho.removeAll();

        for (Produto produto : CarrinhoDeCompras.getProdutos()) {
            ItemDoCarrinhoDeCompras itemDoCarrinhoDeCompras = new ItemDoCarrinhoDeCompras();
            itemDoCarrinhoDeCompras.setProduto(produto, CarrinhoDeCompras.getQuantidadeDoProduto(produto));

            preparaItemMenu(itemDoCarrinhoDeCompras);

            jPanelCarrinho.add(itemDoCarrinhoDeCompras);
            itemDoCarrinhoDeCompras.setVisible(true);
        }
    }

    private void preparaItemMenu(ItemDoCarrinhoDeCompras itemDoCarrinhoDeCompras) {
        itemDoCarrinhoDeCompras.setBounds(x, y, 1000, 124);
        y += 134;
    }

    public void updateCarrinho() {
        initItensDoCarrinhoDeCompras();
        jLabelTotalDaCompra.setText(CarrinhoDeCompras.getValorTotalDaCompra().toString());
        jPanelCarrinho.repaint();
        revalidate();
    }

    private Formadepagamento getFormaDePagamento() {
        if (jRadioButtonPayPal.isSelected()) {
            return FormaDePagamentoControl.findById(1);
        }
        if (jRadioButtonDinheiro.isSelected()) {
            return FormaDePagamentoControl.findById(2);
        }
        if (jRadioButtonVisa.isSelected()) {
            return FormaDePagamentoControl.findById(3);
        }
        return FormaDePagamentoControl.findById(4);
    }

    private boolean areUSure() {
        return JOptionPane.showConfirmDialog(this,
                ConfirmMessages.COMPRAR_CONFIRMACAO.getDescricao(),
                Titles.CONFIRM.getDescricao(),
                JOptionPane.WARNING_MESSAGE,
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }
}
