/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.produto;

import control.CategoriaControl;
import control.FotoControl;
import control.FotoProdutoControl;
import control.ProdutoControl;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import messages.ConfirmMessages;
import messages.Titles;
import model.Categoria;
import model.Foto;
import model.Produto;
import utilidades.ImageChooser;
import utilidades.Imagem;
import utilidades.Mensagens;

/**
 *
 * @author gustavo_yuri
 */
public class EditarProduto extends javax.swing.JFrame {

    DefaultComboBoxModel<Categoria> defaultComboBoxModel = new DefaultComboBoxModel();
    ImageChooser imageChooser = new ImageChooser(this);
    Produto produto = new Produto();
    private Foto produtoFoto;

    /**
     * Creates new form EditarCategoria
     */
    public EditarProduto() {
        initComponents();
        carregaComboBoxCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlProdutoImage = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jtfValor = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jtfQuantidade = new javax.swing.JFormattedTextField();
        jcbCategoria = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição de Produtos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        jPanel1.setMaximumSize(new java.awt.Dimension(110, 110));
        jPanel1.setMinimumSize(new java.awt.Dimension(110, 110));

        jlProdutoImage.setAlignmentY(0.0F);
        jlProdutoImage.setMaximumSize(new java.awt.Dimension(105, 105));
        jlProdutoImage.setMinimumSize(new java.awt.Dimension(105, 105));
        jlProdutoImage.setPreferredSize(new java.awt.Dimension(105, 105));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlProdutoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlProdutoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Img...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbSalvar.setBackground(new java.awt.Color(51, 102, 255));
        jbSalvar.setText("Salvar");
        jbSalvar.setMaximumSize(new java.awt.Dimension(77, 23));
        jbSalvar.setMinimumSize(new java.awt.Dimension(77, 23));
        jbSalvar.setPreferredSize(new java.awt.Dimension(77, 23));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria");

        jLabel4.setText("Qtd.");

        jLabel3.setText("Valor");

        jLabel2.setText("Descricao");

        jLabel1.setText("Nome");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Atenção: Todos os campos são obrigatórios!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNome)
                    .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (isCamposValidados()) {
            if (areUSure()) {
                populaProduto();
                FotoControl.add(produto.getFotoProduto().getFoto());
                FotoProdutoControl.add(produto.getFotoProduto());
                ProdutoControl.add(produto);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imageChooser.setVisible(true);
        if (imageChooser.getSingleImageFile() != null) {
            jlProdutoImage.setIcon(Imagem.resizeImage(100, 100, imageChooser.getSingleImageFile()));
            produtoFoto = imageChooser.getFoto();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProduto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JLabel jlProdutoImage;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JFormattedTextField jtfQuantidade;
    private javax.swing.JFormattedTextField jtfValor;
    // End of variables declaration//GEN-END:variables

    public void setProduto(Produto produto) {
        this.produto = produto;
        produtoFoto = produto.getFotoProduto().getFoto();
        jtfNome.setText(produto.getNome());
        jtfDescricao.setText(produto.getDescricao());
        jtfValor.setText(String.valueOf(produto.getValor()));
        jtfQuantidade.setText(String.valueOf(produto.getQuantidade()));
        jcbCategoria.setSelectedItem(produto.getCategoria());
        jlProdutoImage.setIcon(produto.getFotoProduto().getFoto().getIcon());
    }

    private boolean isCamposValidados() {
        int quantidade = 0;

        if (jtfQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.QUANTIDADE_INVALIDA.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (jtfValor.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.VALOR_INVALIDO.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (jtfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.NOME_INVALIDO.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (jtfDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.DESCRICAO_INVALIDA.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (jlProdutoImage.getIcon() == null || produtoFoto == null) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.IMAGEM_PRODUTO_INVALIDA.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        String produtoValorTratado = jtfValor.getText().replace(',', '.').trim();

        Double valorDouble = (new Double(produtoValorTratado));

        try {
            quantidade = new Integer(jtfQuantidade.getText());
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.QUANTIDADE_INVALIDA.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (valorDouble <= 0) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.VALOR_MENOR_OU_IGUAL_A_ZERO.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(null,
                    Mensagens.QUANTIDADE_MENOR_OU_IGUAL_A_ZERO.getDescricao(),
                    Titles.WARNING.getDescricao(),
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void carregaComboBoxCategoria() {
        for (Categoria categoria : CategoriaControl.listaCategorias()) {
            defaultComboBoxModel.addElement(categoria);
            jcbCategoria.setModel(defaultComboBoxModel);
        }
    }

    private boolean areUSure() {
        return JOptionPane.showConfirmDialog(null,
                ConfirmMessages.EDITAR_CONFIRMACAO.getDescricao(),
                Titles.CONFIRM.getDescricao(),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION;
    }

    private void populaProduto() {
        produto.setNome(jtfNome.getText());
        produto.setDescricao(jtfDescricao.getText());
        produto.setValor(new Double(jtfQuantidade.getText()));
        produto.setQuantidade(new Integer(jtfQuantidade.getText()));
        produto.getFotoProduto().setFoto(produtoFoto);
    }
}
