/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.produto;

import control.ProdutoControl;
import java.util.ArrayList;
import model.Produto;

/**
 *
 * @author gustavo_yuri
 */
public class ListaProdutos extends java.awt.Panel {

    ProdutoControl produtoControle = new ProdutoControl();
    ItemListaProduto itemListaProduto = new ItemListaProduto();
    ArrayList<ItemListaProduto> itemListaProdutos = new ArrayList();

    /**
     * Creates new form ListaProdutos
     */
    public ListaProdutos() {
        initComponents();
        guardaVolumes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelProdutos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBackground(java.awt.Color.blue);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        JLabelProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLabelProdutos.setForeground(new java.awt.Color(255, 255, 255));
        JLabelProdutos.setText("Produtos");

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(JLabelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabelProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelProdutos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void guardaVolumes() {
        int valueX = 0;
        int valueY = 0;
        for (Produto produto : produtoControle.listaProdutos()) {
            ItemListaProduto itemListaProduto = new ItemListaProduto();
            itemListaProduto.populaItemListaProduto(produto);
            //itemListaProdutos.add(itemListaProduto);
//            jPanel1.repaint();
//            jPanel1.revalidate();
            itemListaProduto.setVisible(true);
            itemListaProduto.setBounds(valueX, valueY, 142, 222);            
            if (valueX < 293) {
                valueX += 152;
            } else {
                valueX = 0;
            }
            if (valueX == 152) {
                valueY = 0;
            }else{
                valueY += 232;
            }
            jPanel1.add(itemListaProduto);
        }
    }
}
